# Generated by Django 5.0.6 on 2026-07-01 16:05

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, validators=[django.core.validators.MinLengthValidator(1)])),
                ('description', models.TextField(blank=True, default='')),
                ('color', models.CharField(default='#378ADD', max_length=7)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'projects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#888780', max_length=7)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Haute')], default='medium', max_length=10)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(choices=[('work', 'Travail'), ('personal', 'Personnel'), ('urgent', 'Urgent'), ('other', 'Autre')], default='other', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('done', 'Terminée'), ('archived', 'Archivée')], default='pending', max_length=15)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('position', models.PositiveBigIntegerField(db_index=True, default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='task.project')),
                ('tags', models.ManyToManyField(blank=True, related_name='tasks', to='task.tag')),
            ],
            options={
                'db_table': 'tasks',
                'ordering': ['position', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField(validators=[django.core.validators.MinLengthValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='task.task')),
            ],
            options={
                'db_table': 'task_comments',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['owner', 'is_archived'], name='idx_project_owner_archived'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(condition=models.Q(('is_deleted', False)), fields=['owner', 'status'], name='idx_task_owner_status'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'priority'], name='idx_task_owner_priority'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['owner', 'due_date'], name='idx_task_due_date'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['project'], name='idx_task_project'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['position'], name='idx_task_position'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(check=models.Q(('due_date__isnull', True), ('due_date__gt', models.F('created_at')), _connector='OR'), name='chk_due_date_after_created'),
        ),
        migrations.AddIndex(
            model_name='taskcomment',
            index=models.Index(fields=['task', 'created_at'], name='idx_comment_task_ts'),
        ),
    ]
