# Generated by Django 5.0.6 on 2026-07-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
